# Database URL, Username, and Password Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sakthi123

# Hibernate/JPA Properties to auto-create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server Port Setup
server.port=8080
